export const availableIndicators = [
  { name: 'Relative Strength Index', resource: 'rsi' },
  { name: 'Stochastic RSI', resource: 'stochasticrsi' },
  { name: 'Moving Average Convergence Divergence', resource: 'macd' },
  { name: 'Rate of Change', resource: 'roc' },
  { name: 'Accumulation Distribution Line', resource: 'adl' },
  { name: 'Average Directional Index', resource: 'adx' },
  { name: 'Average True Range', resource: 'atr' },
  { name: 'Awesome Oscillator', resource: 'awesomeOscillator' },
  { name: 'Bollinger Bands', resource: 'bollingerBands' },
  { name: 'Commodity Channel Index', resource: 'cci' },
  { name: 'Force Index', resource: 'forceIndex' },
  { name: 'Know Sure Thing', resource: 'knowSureThing' },
  { name: 'Monetflow Index', resource: 'moneyFlowIndex' },
  { name: 'On Balance Volume', resource: 'onBalanceVolume' },
  { name: 'Parabolic Stop and Reverse', resource: 'parabolicStopAndReverse' },
  { name: 'Simple Moving Average', resource: 'simpleMovingAverage' },
  { name: 'Stochastic Oscilator', resource: 'stochasticOscilator' },
  { name: 'Triple Exponentially Smoothed Average', resource: 'trix' },
  { name: 'Volume Weighted Average Price', resource: 'vwap' },
  { name: 'Volume Profile', resource: 'volumeProfile' },
  { name: 'Exponential Moving Average', resource: 'ema' },
  { name: 'Weighted Moving Average', resource: 'wma' },
  { name: 'Wilder’s Smoothing (Smoothed Moving Average)', resource: 'wema' },
  { name: 'WilliamsR', resource: 'williamsR' },
  { name: 'Ichimoku Cloud', resource: 'ichimokuCloud' },
]